version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  pulsar:
    image: apachepulsar/pulsar:2.6.4
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: bin/pulsar standalone

  caliban:
    build:
      dockerfile: Dockerfile-Caliban
    ports:
      - "8088"

  backend:
    build:
      dockerfile: Dockerfile-Back

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - caliban
    ports:
      - "8088:8088"
