version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  pulsar:
    image: apachepulsar/pulsar:2.6.4
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: bin/pulsar standalone

  caliban:
    build:
      dockerfile: Dockerfile-Caliban
      context: .
    environment:
      REDIS_HOST: "redis"
      PULSAR_HOST: "pulsar"
    ports:
      - "8088"

  backend:
    build:
      dockerfile: Dockerfile-Backend
      context: .
    environment:
      REDIS_HOST: "redis"
      PULSAR_HOST: "pulsar"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8088:8088"
